specVersion: 0.2.0
name: nova
version: 1.0.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-nova
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xca93a37c913a25fa8fdb33c7f738afc39379cb71d37874a16d4c091a5aef9f89'
  endpoint: wss://imbue-kusama.imbue.network

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/src/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleParachainRewarded
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
        - handler: handleAssetTransfer
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleCurrencyTransfer
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleTokenTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer