specVersion: 0.2.0
name: nova
version: 1.0.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-nova
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfeb426ca713f0f46c96465b8f039890370cf6bfd687c9076ea2843f58a6ae8a7'
  endpoint: 'wss://kabocha.jelliedowl.com'

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/src/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleParachainRewarded
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
        - handler: handleAssetTransfer
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred
        - handler: handleCurrencyTransfer
          kind: substrate/EventHandler
          filter:
            module: currencies
            method: Transferred
        - handler: handleTokenTransfer
          kind: substrate/EventHandler
          filter:
            module: tokens
            method: Transfer