name: Deploy subquery to stage (without reindex)

on:
  workflow_dispatch

env:
  SUBQUERY_CLI_VERSION: 0.2.5
  SUBQUERY_ORG: nova-wallet
  INDEXER_IMAGE_VERSION: v0.31.1
  QUERY_IMAGE_VERSION: v0.13.0

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v2

    - id: set-matrix
      run: |
        folders=($(ls ./networks))

        JSON="{\"include\":["

        for item in ${folders[*]}
        do
            JSONline="{\"chain\": \"$item\"},"

            if [[ "$JSON" != *"$JSONline"* ]]; then
                JSON="$JSON$JSONline"
            fi
            echo $item
        done <<< "$DIFF"

        # Remove last "," and add closing brackets
        if [[ $JSON == *, ]]; then
          JSON="${JSON%?}"
        fi
        JSON="$JSON]}"
        echo $JSON

        echo "::set-output name=matrix::$( echo "$JSON" )"

  deploy-subquery:
    needs: setup
    name: Deploy subquery
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix: ${{fromJson(needs.setup.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          mkdir -p $HOME/.local/bin
          curl -LO https://github.com/fewensa/subquery-cli/releases/download/v${{ env.SUBQUERY_CLI_VERSION }}/subquery-linux-x86_64.zip
          unzip subquery-linux-x86_64.zip -d $HOME/.local/bin/
          rm -rf subquery-linux-x86_64.zip
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Deploy
        run: |
          subquery --token ${{ secrets.SUBQUERY_TOKEN }} deployment deploy \
            --org ${{ env.SUBQUERY_ORG }} \
            --key nova-wallet-${{ matrix.chain }} \
            --branch deploy \
            --sub-folder ./networks/${{ matrix.chain }} \
            --type stage \
            --indexer-image-version ${{ env.INDEXER_IMAGE_VERSION }} \
            --query-image-version ${{ env.QUERY_IMAGE_VERSION }} \
            --indexer-batch-size 15
